[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install -r der-tisch-backend/requirements.txt"
]

[start]
cmd = "cd der-tisch-backend && uvicorn api_server:app --host 0.0.0.0 --port $PORT"
